export const PRIMARY_KEYWORDS = [
  'ai assistant',
  'ai chatbot',
  'llm',
  'openai',
  'langchain',
  'rag',
  'retrieval augmented',
  'saas',
  'full stack',
  'fullstack',
  'react',
  'next.js',
  'nextjs',
  'node.js',
  'nodejs',
  'ai agent',
  'conversational ai',
  'voice ai',
  'elevenlabs',
  'deepseek',
  'mistral',
  'vector database',
  'ai integration',
  'crm',
  'dashboard',
  'api integration',
  'rest api',
] as const;

export const SECONDARY_KEYWORDS = [
  'typescript',
  'nestjs',
  'postgresql',
  'mysql',
  'redis',
  'aws',
  'docker',
  'vercel',
  'real-time',
  'websocket',
  'webhook',
  'mobile app',
  'react native',
  'nuxt',
  'vue',
  'vuejs',
  'express',
  'mongodb',
  'prisma',
] as const;

export const DISQUALIFYING_KEYWORDS = [
  'wordpress',
  'shopify',
  'woocommerce',
  'php',
  'laravel',
  'flutter only',
  'java only',
  'python only',
  'django only',
  'ruby on rails',
  'angular',
  'svelte',
  'blockchain',
  'smart contract',
  'solidity',
  'web3',
  'unity',
  'game dev',
  'devops only',
  'data science',
  'machine learning model training',
  'ios swift',
  'android kotlin',
  'c#',
  '.net',
  'asp.net',
] as const;

export const TEMPLATE_1_KEYWORDS = [
  'ai assistant',
  'chatbot',
  'llm',
  'conversational ai',
  'ai agent',
  'voice ai',
  'openai',
  'rag',
  'langchain',
  'ai integration',
  'deepseek',
  'mistral',
  'elevenlabs',
] as const;

export const TEMPLATE_2_KEYWORDS = [
  'saas',
  'crm',
  'dashboard',
  'platform',
  'portal',
  'management system',
  'erp',
  'admin panel',
  'workflow',
  'business software',
  'scheduling',
  'billing',
  'inventory',
] as const;

export const TEMPLATE_3_KEYWORDS = [
  'react',
  'next.js',
  'nextjs',
  'frontend',
  'full stack',
  'fullstack',
  'web app',
  'web application',
  'node.js',
  'nodejs',
] as const;
